---
title: "PS270 Final Project"
author: "Grace Fragakis"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to fashion, or environmental issues. I would consider combining the two and finding data related to environmental damages in different countries due to fashion trends or consumerism. 

I am also interested in exploring data related to the amount of soda consumed in each state of the United states, specifically Diet Dr. Pepper. 

Furthermore, I am also interested in exploring data related to the size of celebrities carbon footprint compared to the average human in the US. 

## Proposal

For my research question I will be exploring: How does increasing atmospheric carbon dioxide concentration affect global weather patterns? Carbon dioxide emissions are most prominently caused by us humans, and our consumerism. Between traveling, buying, and using, all of our carbon footprints put our planet in danger. I believe that carbon dioxide concentrations in our environment and global weather patterns are directly correlated. Therefore, if carbon emissions are increased then I think that there will be more frequent and intense extreme weather events.  My explanatory variable that I would measure is the carbon dioxide concentration in the atmosphere, which is measured by parts per million. My outcome variable of interest is the frequency of extreme weather events and that would be measured by frequency of the events. The observed pattern in data that would support my hypothesis are higher carbon dioxide levels leading to more extreme weather events. To disprove my hypothesis the pattern of higher carbon dioxide emissions with less extreme weather events would have to be recorded. 
